config/routes.rb
YelpMyVersion::Application.routes.draw do
 root 'restaurants#index'

  
  resources :restaurants do
    resources :images, only: [:index]
    resources :reviews, only: [:index,:show]
  end

  

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews
	has_many :images
	accepts_nested_attributes_for :reviews

	validates :name, :presence => true

	def add_image(url)
		images << Image.create(:url =>url)
	end

	def add_review(content)
		reviews << Review.create(:content =>content)
	end
	def add_raitings(raiting)
		reviews << Review.create(:raitings =>raiting)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	def index
		images =Image.all
		render json: images.map{|i| i.url}
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants =Restaurant.all.order("restaurants.name ASC").limit(10)
		@reviews =Review.all

	end


	def new
		@restaurant=Restaurant.new
		@restaurant.reviews.build if @restaurant.reviews.empty?
	end

	def show
		@restaurant=Restaurant.find(params[:id])
		
	end


	# def create
	# 	@restaurant =Restaurant.new(params[:restaurant]).permit(:name, :description)
	# 	if @restaurant.save
	# 		redirect_to('/restaurants')
	# 	else
	# 		render('new')
	# 	end
	# end

	def create
		@restaurant=Restaurant.new(rest_params)

		if @restaurant.save
			flash.now[:notice] ="Updated !!"
			redirect_to @restaurant
		else
			flash.now[:errors] = @restaurant.errors.full_messages.join('')
			render('new')
		end
	end

	def edit
		@restaurant=Restaurant.find(params[:id])
		@restaurant.reviews.build if @restaurant.reviews.empty?
	end

	def update
		@restaurant=Restaurant.find(params[:id])

		if @restaurant.update_attributes(rest_params)
			flash[:notice] ="Your Record was updated"
			redirect_to(:action =>'show',:id =>@restaurant.id)
		else
			flash.now[:errors] = @restaurant.errors.full_messages.join('')
			render('edit')
		end
	end

	private
	def rest_params
    	params.require(:restaurant).permit(:name, :description, reviews_attributes: [:id, :content])
  	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
		@reviews =Review.all
		render :reviews_index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">MyYelp App</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      
      <li ><%= link_to "Sign in", ""%></li>
      <li ><%= link_to "Sign up", "#"%></li>
      <li ><%= link_to "Home", restaurants_path %></li>
      <%= yield :nav %>
      <li ><%= link_to "Create New", new_restaurant_path%></li> 
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_my_tweets.html.erb
<!-- include the jQuery library if you haven't already -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

<!-- include the GMTweets library, keep this hosted to our servers to ensure you stay up-to date -->
<script src="http://api.getmytweets.co.uk/min.tweet.3.js"></script>

<!-- the plugin -->
<script type="text/javascript">
$(document).ready(function(e) {
    
    $('.twitter_feed').getmytweets({
        twitter_sn: 'itservicesgroup', /* my twitter username */
        twitter_wrap: 'tweet', /* wrap each tweet with a class */
        twitter_limit: 10, /* how many tweets to return */
        twitter_pp: false, /* display your profile picture */
        twitter_stats: false, /* display your twitter stats */
        twitter_details: false /* display your details (name, location) */
    });
    
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpMyVersion</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class="container">
	<%=render "layouts/header"%>
	</div>
	<div class="container">

		<%= yield %>
	</div>
</body>
</html>

app/views/restaurants/create.html.erb
<p>Added new record</p>

app/views/restaurants/edit.html.erb
<p class="lead">Edit Record of a restaurant </p>
<%=form_for @restaurant do |f| %>
<div class="flash">
	<%= flash[:errors] %>
</div>
<div class="form-group">
	<%= f.label :name ,'Name',class: "sr-only"%>
	<%= f.text_field :name, placeholder: "Edit Restaurant" %>
	<%= f.label :description ,'Description',class: "sr-only"%>
	<%= f.text_field :description, placeholder: "Description" %>
</br></br>
	<%= f.fields_for :reviews do |review_f| %>
		<%= review_f.text_area :content ,placeholder:"Review this restaurant" ,rows: "10" ,cols: "48" %>
	<% end %>
</br></br>
	<%=f.submit class: "btn btn-default"%>
</div>

<% end%>

app/views/restaurants/index.html.erb
<div class="jumbotron">
	<h3 class="center">Welcome to myYelp</h3>
</div>
<% @restaurants.each do |restaurant| %>
	<div>
		<%= link_to restaurant.name, restaurant%>
		<% restaurant.reviews.each do |review| %>
			<span class="comment">Comments: <%=review.content %></span>
		<% end%>
	</div>	
<% end%>

app/views/restaurants/new.html.erb
<p class="lead">Create new record of a restaurant </p>
<%=form_for @restaurant do |f| %>
<div class="flash">
	<%= flash[:errors] %>
</div>
<div class="form-group">
	<%= f.label :name ,'Name',class: "sr-only"%>
	<%= f.text_field :name, placeholder: "New Restaurant" %>
	<%= f.label :description ,'Description',class: "sr-only"%>
	<%= f.text_field :description, placeholder: "Description" %>
	</br></br>
	<%= f.fields_for :reviews do |review_f| %>
		<%= review_f.text_area :content ,placeholder:"Review this restaurant" ,rows: "10" ,cols: "46" %>
	<% end %>
</br>
	<div class='radio_b'>
		<% 1.upto(5) do |n| %> 
			<label>
				<% n.times do %>
					<%= image_tag('http://2.bp.blogspot.com/-Qv4StauwsKo/TjfsduadV8I/AAAAAAAAQsU/ffcRG6MIUrE/s1600/Gold-star-2-1.jpg', size: '20x20') %>
				<% end %>
				<%= radio_button_tag(:raitings, n) %>
			</label>
			</br>
		<% end %>
	</div>
</br>
	<%=f.submit class: "btn btn-default"%>
</div>
<% end%>

app/views/restaurants/show.html.erb
<% content_for :nav do %>
	<li ><%= link_to "Edit Record",edit_restaurant_path(@restaurant)%></li>
<% end %>

<H3>Personal Webpage for <%= @restaurant.name %> </H3>
<p>Available in: <%=@restaurant.description %></p>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
<div id="image_link">
	<%=link_to  "link", restaurant_images_path(@restaurant), remote: true %>
<div id="put_here"></div>
	<a href='#' id="fade">Close</a>
</div>
<div class="twitter_feed"></div>

app/views/reviews/reviews_index.html.erb
<p>Hello there ! </p>